# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 01:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AqicnIAqiData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_point', models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('date', models.DateField(default=datetime.date(2017, 3, 19), verbose_name='\u65e5\u671f')),
                ('aqi', models.FloatField(blank=True, default=None, null=True, verbose_name='AQI\u503c')),
                ('dominentpol', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4e3b\u8981\u6c61\u67d3\u7269')),
                ('pm25_iaqi', models.FloatField(blank=True, null=True, verbose_name='pm25 iaqi\u503c(1h)')),
                ('pm10_iaqi', models.FloatField(blank=True, null=True, verbose_name='pm20 iaqi\u503c(1h)')),
                ('o3_iaqi', models.FloatField(blank=True, null=True, verbose_name='o3 iaqi\u503c(1h)')),
                ('no2_iaqi', models.FloatField(blank=True, null=True, verbose_name='no2 iaqi\u503c(1h)')),
                ('so2_iaqi', models.FloatField(blank=True, null=True, verbose_name='so2 iaqi\u503c(1h)')),
                ('co_iaqi', models.FloatField(blank=True, null=True, verbose_name='co iaqi\u503c(1h)')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='\u6e29\u5ea6')),
                ('dew', models.FloatField(blank=True, null=True, verbose_name='\u9732\u70b9')),
                ('atmospheric_pressure', models.IntegerField(blank=True, null=True, verbose_name='\u5927\u6c14\u538b')),
                ('relative_humidity', models.FloatField(blank=True, null=True, verbose_name='\u76f8\u5bf9\u6e7f\u5ea6')),
                ('wind', models.FloatField(blank=True, null=True, verbose_name='\u98ce\u529b')),
            ],
            options={
                'db_table': 'aqicniaqidata',
            },
        ),
        migrations.CreateModel(
            name='ChinaStandard',
            fields=[
                ('quality', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u7a7a\u6c14\u8d28\u91cf\u7b49\u7ea7')),
                ('message', models.CharField(max_length=255, verbose_name='\u5efa\u8bae\u4fe1\u606f')),
            ],
            options={
                'db_table': 'chinastandard',
            },
        ),
        migrations.CreateModel(
            name='GzepbAqiData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_point', models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('date', models.DateField(default=datetime.date(2017, 3, 19), verbose_name='\u65e5\u671f')),
                ('aqi', models.FloatField(blank=True, null=True, verbose_name='AQI\u503c')),
                ('dominentpol', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4e3b\u8981\u6c61\u67d3\u7269')),
                ('so2_1h', models.FloatField(blank=True, null=True, verbose_name='so2 1h\u6d53\u5ea6')),
                ('so2_24h', models.FloatField(blank=True, null=True, verbose_name='so2 24h\u6ed1\u52a8\u5e73\u5747\u6d53\u5ea6')),
                ('no2_1h', models.FloatField(blank=True, null=True, verbose_name='no2 1h\u6d53\u5ea6')),
                ('no2_24h', models.FloatField(blank=True, null=True, verbose_name='no2 24h\u6ed1\u52a8\u5e73\u5747\u6d53\u5ea6')),
                ('pm10_1h', models.FloatField(blank=True, null=True, verbose_name='pm10 1h\u6d53\u5ea6')),
                ('pm10_24h', models.FloatField(blank=True, null=True, verbose_name='pm10 24h\u6ed1\u52a8\u5e73\u5747\u6d53\u5ea6')),
                ('co_1h', models.FloatField(blank=True, null=True, verbose_name='co 1h\u6d53\u5ea6')),
                ('co_24h', models.FloatField(blank=True, null=True, verbose_name='co 24h\u6ed1\u52a8\u5e73\u5747\u6d53\u5ea6')),
                ('o3_1h', models.FloatField(blank=True, null=True, verbose_name='o3 1h\u6d53\u5ea6')),
                ('o3_1h_24h', models.FloatField(blank=True, null=True, verbose_name='o3 \u6700\u59271h\u6d53\u5ea6(24h\u5185)')),
                ('o3_8h', models.FloatField(blank=True, null=True, verbose_name='o3 8h\u6ed1\u52a8\u5e73\u5747\u6d53\u5ea6')),
                ('o3_8h_24h', models.FloatField(blank=True, null=True, verbose_name='o3 \u6700\u59278h\u6ed1\u52a8\u5e73\u5747\u6d53\u5ea6(24h\u5185)')),
                ('pm25_1h', models.FloatField(blank=True, null=True, verbose_name='pm25 1h\u6d53\u5ea6')),
                ('pm25_24h', models.FloatField(blank=True, null=True, verbose_name='pn24 24h\u6ed1\u52a8\u5e73\u5747\u6d53\u5ea6')),
                ('so2_aqi', models.FloatField(blank=True, null=True, verbose_name='so2 iaqi\u503c(1h)')),
                ('no2_aqi', models.FloatField(blank=True, null=True, verbose_name='no2 iaqi\u503c(1h)')),
                ('pm10_aqi', models.FloatField(blank=True, null=True, verbose_name='pm10 iaqi\u503c(1h)')),
                ('co_aqi', models.FloatField(blank=True, null=True, verbose_name='co iaqi\u503c(1h)')),
                ('o3_aqi', models.FloatField(blank=True, null=True, verbose_name='o3 iaqi\u503c(1h)')),
                ('o3_aqi_8h', models.FloatField(blank=True, null=True, verbose_name='o3 iaqi\u503c(8h)')),
                ('pm25_aqi', models.FloatField(blank=True, null=True, verbose_name='pm25 iaqi\u503c(1h)')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.ChinaStandard', verbose_name='\u7a7a\u6c14\u8d28\u91cf\u7b49\u7ea7')),
            ],
            options={
                'db_table': 'gzepbaqidata',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u76d1\u6d4b\u70b9\u540d\u79f0')),
                ('station_type', models.CharField(choices=[('city_average', '\u57ce\u5e02\u5747\u503c'), ('evaluate_point', '\u57ce\u5e02\u8bc4\u4ef7\u70b9'), ('trendency_point', '\u57ce\u5e02\u8d8b\u52bf\u70b9'), ('national_point', '\u56fd\u63a7\u70b9'), ('roadside_point', '\u8def\u8fb9\u7ad9'), ('contrast_national_point', '\u56fd\u63a7\u5bf9\u7167\u70b9'), ('us_consulate_point', '\u7f8e\u56fd\u9886\u4e8b\u9986\u70b9')], max_length=25, verbose_name='\u76d1\u6d4b\u70b9\u7c7b\u578b')),
                ('display_name', models.CharField(blank=True, max_length=30, verbose_name='\u76d1\u6d4b\u70b9\u663e\u793a\u540d\u79f0')),
                ('latitude', models.FloatField(blank=True, default=None, null=True, verbose_name='\u7eac\u5ea6')),
                ('longitude', models.FloatField(blank=True, default=None, null=True, verbose_name='\u7ecf\u5ea6')),
                ('city', models.CharField(max_length=10, verbose_name='\u57ce\u5e02')),
                ('district', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u884c\u653f\u533a')),
                ('center', models.BooleanField(default=False, max_length=5, verbose_name='\u662f\u5426\u5e02\u4e2d\u5fc3')),
            ],
            options={
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='USAStandard',
            fields=[
                ('quality', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u7a7a\u6c14\u8d28\u91cf\u7b49\u7ea7')),
                ('message', models.CharField(max_length=255, verbose_name='\u5efa\u8bae\u4fe1\u606f')),
            ],
            options={
                'db_table': 'usastandard',
            },
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together=set([('station_name', 'station_type')]),
        ),
        migrations.AddField(
            model_name='gzepbaqidata',
            name='station_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Station', verbose_name='\u76d1\u6d4b\u70b9'),
        ),
        migrations.AddField(
            model_name='aqicniaqidata',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.USAStandard', verbose_name='\u7a7a\u6c14\u8d28\u91cf\u7b49\u7ea7'),
        ),
        migrations.AddField(
            model_name='aqicniaqidata',
            name='station_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Station', verbose_name='\u76d1\u6d4b\u70b9'),
        ),
        migrations.AlterUniqueTogether(
            name='gzepbaqidata',
            unique_together=set([('station_name', 'time_point')]),
        ),
        migrations.AlterUniqueTogether(
            name='aqicniaqidata',
            unique_together=set([('station_name', 'time_point')]),
        ),
    ]
