# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 02:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqicniaqidata',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='gzepbaqidata',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='\u65e5\u671f'),
        ),
    ]
