# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20170319_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u76d1\u6d4b\u70b9\u663e\u793a\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='\u76d1\u6d4b\u70b9\u540d\u79f0'),
        ),
    ]
