# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20170319_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gzepbaqidata',
            old_name='co_aqi',
            new_name='co_iaqi',
        ),
        migrations.RenameField(
            model_name='gzepbaqidata',
            old_name='no2_aqi',
            new_name='no2_iaqi',
        ),
        migrations.RenameField(
            model_name='gzepbaqidata',
            old_name='o3_aqi',
            new_name='o3_iaqi',
        ),
        migrations.RenameField(
            model_name='gzepbaqidata',
            old_name='o3_aqi_8h',
            new_name='o3_iaqi_8h',
        ),
        migrations.RenameField(
            model_name='gzepbaqidata',
            old_name='pm10_aqi',
            new_name='pm10_iaqi',
        ),
        migrations.RenameField(
            model_name='gzepbaqidata',
            old_name='pm25_aqi',
            new_name='pm25_iaqi',
        ),
        migrations.RenameField(
            model_name='gzepbaqidata',
            old_name='so2_aqi',
            new_name='so2_iaqi',
        ),
        migrations.AlterField(
            model_name='station',
            name='station_type',
            field=models.CharField(choices=[('\u57ce\u5e02\u5747\u503c', '\u57ce\u5e02\u5747\u503c'), ('\u57ce\u5e02\u8bc4\u4ef7\u70b9', '\u57ce\u5e02\u8bc4\u4ef7\u70b9'), ('\u57ce\u5e02\u8d8b\u52bf\u70b9', '\u57ce\u5e02\u8d8b\u52bf\u70b9'), ('\u56fd\u63a7\u70b9', '\u56fd\u63a7\u70b9'), ('\u8def\u8fb9\u7ad9', '\u8def\u8fb9\u7ad9'), ('\u56fd\u63a7\u5bf9\u7167\u70b9', '\u56fd\u63a7\u5bf9\u7167\u70b9'), ('\u7f8e\u56fd\u9886\u4e8b\u9986\u70b9', '\u7f8e\u56fd\u9886\u4e8b\u9986\u70b9')], max_length=25, verbose_name='\u76d1\u6d4b\u70b9\u7c7b\u578b'),
        ),
    ]
