# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170320_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='AqiStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqi_range', models.CharField(max_length=20, verbose_name='AQI\u8303\u56f4')),
                ('usa_quality', models.CharField(max_length=20, verbose_name='\u7f8e\u56fd\u6807\u51c6\u7a7a\u6c14\u8d28\u91cf\u7b49\u7ea7')),
                ('china_quality', models.CharField(max_length=20, verbose_name='\u4e2d\u56fd\u6807\u51c6\u7a7a\u6c14\u8d28\u91cf\u7b49\u7ea7')),
                ('color', models.CharField(max_length=5, verbose_name='\u7b49\u7ea7\u989c\u8272')),
                ('message', models.CharField(max_length=255, verbose_name='\u5bf9\u5065\u5eb7\u5f71\u54cd')),
                ('advice', models.CharField(max_length=255, verbose_name='\u5efa\u8bae\u63aa\u65bd')),
            ],
            options={
                'db_table': 'aqistandard',
            },
        ),
        migrations.AlterField(
            model_name='aqicniaqidata',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.AqiStandard', verbose_name='\u7a7a\u6c14\u8d28\u91cf\u7b49\u7ea7'),
        ),
        migrations.AlterField(
            model_name='gzepbaqidata',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.AqiStandard', verbose_name='\u7a7a\u6c14\u8d28\u91cf\u7b49\u7ea7'),
        ),
        migrations.DeleteModel(
            name='ChinaStandard',
        ),
        migrations.DeleteModel(
            name='USAStandard',
        ),
    ]
