# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 09:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20170322_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='GzepbAqiDataUsaStandard',
            fields=[
                ('origin_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.GzepbAqiData', verbose_name='\u539f\u59cb\u6570\u636e')),
                ('time_point', models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='\u65e5\u671f')),
                ('aqi', models.FloatField(blank=True, null=True, verbose_name='AQI\u503c')),
                ('dominentpol', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4e3b\u8981\u6c61\u67d3\u7269')),
                ('so2_iaqi', models.FloatField(blank=True, null=True, verbose_name='so2 iaqi\u503c(1h)')),
                ('no2_iaqi', models.FloatField(blank=True, null=True, verbose_name='no2 iaqi\u503c(1h)')),
                ('pm10_iaqi', models.FloatField(blank=True, null=True, verbose_name='pm10 iaqi\u503c(1h)')),
                ('co_iaqi', models.FloatField(blank=True, null=True, verbose_name='co iaqi\u503c(1h)')),
                ('o3_iaqi_8h', models.FloatField(blank=True, null=True, verbose_name='o3 iaqi\u503c(8h)')),
                ('pm25_iaqi', models.FloatField(blank=True, null=True, verbose_name='pm25 iaqi\u503c(1h)')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.AqiStandard', verbose_name='\u7a7a\u6c14\u8d28\u91cf\u7b49\u7ea7')),
                ('station_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Station', verbose_name='\u76d1\u6d4b\u70b9')),
            ],
            options={
                'db_table': 'gzepbaqidata_usastanard',
            },
        ),
        migrations.AlterUniqueTogether(
            name='gzepbaqidatausastandard',
            unique_together=set([('station_name', 'time_point')]),
        ),
    ]
