# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20170414_1754'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gzepbaqidatausastandard',
            table='gzepbaqidata_usastandard',
        ),
    ]
